### ISSUE TITLE
Add class to apply machine learning to new tweets

### ISSUE THREAD

**Issue by Nebelhom** [Nebelhom/tweetery#40]
This is a tracking issue for several sub-issues revolving around using machine learning to classify newly downloaded tweets from TweetCollector.

- [x] Add text processing to bag-of-words for each tweet #41 
- [x] Train/Recalibrate the model (allow different classifiers and use grid, with a pipe) #42
- [x] Save trained model and nltk portions to be reloaded (no need for retraining each time), either pickle or SQL #43

**Comment by Nebelhom** [comment]
All 3 sub-issues have been completed, therefore I can close this issue, too.
